[db]
host = "zephyr.proxy.rlwy.net"
port = 3306
user = "root"
password = "rLrTwcJBEiHIEhFdIfoTHrZZeKtaxcvn"
database = "railway"

[email]
address = "onlinequizapp7@gmail.com"
app_password = "zxua kmkf rzxi sceg"
